-- Project Polaris: PostgreSQL Database Schema
-- Organized by logical layers: raw, clean, analytics, features, predictions

---------------------------------------------------------
-- 1. SCHEMAS
---------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS clean;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS features;
CREATE SCHEMA IF NOT EXISTS predictions;

---------------------------------------------------------
-- 2. RAW LAYER
-- Staging tables for unmodified data from external sources
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS raw.apify_places (
    id SERIAL PRIMARY KEY,
    source_url TEXT,
    raw_data JSONB,
    extracted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raw.google_maps_data (
    id SERIAL PRIMARY KEY,
    place_id TEXT,
    raw_json JSONB,
    extracted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raw.external_reviews (
    id SERIAL PRIMARY KEY,
    source_platform VARCHAR(50),
    raw_review JSONB,
    extracted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raw.weather_data (
    id SERIAL PRIMARY KEY,
    location_id TEXT,
    weather_json JSONB,
    recorded_at TIMESTAMP
);

---------------------------------------------------------
-- 3. CLEAN LAYER
-- Normalized, strictly typed data
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS clean.businesses (
    business_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    place_id TEXT UNIQUE,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    category VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clean.reviews (
    review_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES clean.businesses(business_id),
    platform VARCHAR(50),
    rating DECIMAL(3, 2),
    review_text TEXT,
    author_name VARCHAR(255),
    published_at TIMESTAMP,
    cleaned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clean.weather_metrics (
    metric_id SERIAL PRIMARY KEY,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    temperature_c DECIMAL(5, 2),
    precipitation_mm DECIMAL(5, 2),
    recorded_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clean.demographics (
    region_code VARCHAR(50) PRIMARY KEY,
    population INT,
    median_income DECIMAL(12, 2),
    median_age DECIMAL(4, 1),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

---------------------------------------------------------
-- 4. ANALYTICS LAYER
-- Aggregated views and metrics for KPIs and reporting
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS analytics.business_kpis (
    kpi_id SERIAL PRIMARY KEY,
    business_id UUID REFERENCES clean.businesses(business_id),
    report_date DATE,
    average_rating DECIMAL(3, 2),
    review_count INT,
    sentiment_score DECIMAL(5, 4),
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analytics.competitor_metrics (
    id SERIAL PRIMARY KEY,
    target_business_id UUID REFERENCES clean.businesses(business_id),
    competitor_business_id UUID REFERENCES clean.businesses(business_id),
    distance_km DECIMAL(6, 2),
    rating_difference DECIMAL(3, 2),
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

---------------------------------------------------------
-- 5. FEATURE TABLES
-- Prepared datasets for Machine Learning pipelines
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS features.store_performance_features (
    feature_id SERIAL PRIMARY KEY,
    business_id UUID REFERENCES clean.businesses(business_id),
    date DATE,
    rolling_7d_rating DECIMAL(3, 2),
    weather_temp_c DECIMAL(5, 2),
    local_event_flag BOOLEAN,
    demographic_income DECIMAL(12, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

---------------------------------------------------------
-- 6. PREDICTION TABLES
-- Outputs generated by ML models (Forecasting, Recommendation)
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS predictions.revenue_forecasts (
    forecast_id SERIAL PRIMARY KEY,
    business_id UUID REFERENCES clean.businesses(business_id),
    forecast_date DATE,
    predicted_revenue DECIMAL(15, 2),
    confidence_lower DECIMAL(15, 2),
    confidence_upper DECIMAL(15, 2),
    model_version VARCHAR(50),
    predicted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS predictions.ai_insights (
    insight_id SERIAL PRIMARY KEY,
    business_id UUID REFERENCES clean.businesses(business_id),
    insight_type VARCHAR(100),
    narrative_text TEXT,
    generated_by VARCHAR(50), -- e.g., 'gemini-1.5-pro'
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
